/*
 * Copyright (c) 2026 Erik A. Brandstadmoen (C# port modifications/adaptations).
 * Mechanically converted from Apache PDFBox Java source with AI assistance.
 *
 * PDFBOX_SOURCE_PATH: examples/src/main/java/org/apache/pdfbox/examples/interactive/form/AddBorderToField.java
 * PDFBOX_SOURCE_COMMIT: eeb5d611e0cea8beac3d7025a4dbccbef51d5caf
 * PORT_MODE: mechanical
 * PORT_LAST_SYNC_COMMIT: eeb5d611e0cea8beac3d7025a4dbccbef51d5caf
 */

/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using PdfBox.Net;
using PdfBox.Net.COS;
using PdfBox.Net.PDModel;
using PdfBox.Net.PDModel.Graphics.Color;
using PdfBox.Net.PDModel.Interactive.Annotation;
using PdfBox.Net.PDModel.Interactive.Form;

namespace PdfBox.Net.Examples.Interactive.Form;

/// <summary>
/// Add a border to an existing field.
///
/// This sample adds a border to a field.
///
/// This sample builds on the form generated by <see cref="CreateSimpleForm"/> so you need to run
/// that first.
/// </summary>
public sealed class AddBorderToField
{
    internal const string ResultFilename = "target/AddBorderToField.pdf";

    private AddBorderToField()
    {
    }

    public static void Main(string[] args)
    {
        // Load the PDF document created by CreateSimpleForm
        using (PDDocument document = Loader.LoadPDF(CreateSimpleForm.DefaultFilename))
        {
            PDAcroForm acroForm = document.GetDocumentCatalog().GetAcroForm()!;

            // Get the field and the widget associated to it.
            // Note: there might be multiple widgets
            PDField field = acroForm.GetFieldTree().First(f => f.GetPartialName() == "SampleField");
            PDAnnotationWidget widget = field.GetWidgets()[0];

            // Create the definition for a red border
            PDAppearanceCharacteristicsDictionary fieldAppearance =
                new PDAppearanceCharacteristicsDictionary(new COSDictionary());
            PDColor red = new PDColor(new float[] { 1, 0, 0 }, PDDeviceRGB.Instance);
            fieldAppearance.SetBorderColour(red);

            // Set the information to be used by the widget which is responsible
            // for the visual style of the form field.
            widget.SetAppearanceCharacteristics(fieldAppearance);

            document.Save(ResultFilename);
        }
    }
}
