/*
 * Copyright (c) 2026 Erik A. Brandstadmoen (C# port modifications/adaptations).
 * Mechanically converted from Apache PDFBox Java source with AI assistance.
 *
 * PDFBOX_SOURCE_PATH: examples/src/main/java/org/apache/pdfbox/examples/interactive/form/DetermineTextFitsField.java
 * PDFBOX_SOURCE_COMMIT: eeb5d611e0cea8beac3d7025a4dbccbef51d5caf
 * PORT_MODE: mechanical
 * PORT_LAST_SYNC_COMMIT: eeb5d611e0cea8beac3d7025a4dbccbef51d5caf
 */

/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using PdfBox.Net;
using PdfBox.Net.COS;
using PdfBox.Net.PDModel;
using PdfBox.Net.PDModel.Font;
using PdfBox.Net.PDModel.Interactive.Annotation;
using PdfBox.Net.PDModel.Interactive.Form;
using PdfBox.Net.PDModel.Resources;

namespace PdfBox.Net.Examples.Interactive.Form;

/// <summary>
/// Determine if text length fits the field.
///
/// This sample builds on the form generated by <see cref="CreateSimpleForm"/> so you need to run
/// that first.
/// </summary>
public sealed class DetermineTextFitsField
{
    private DetermineTextFitsField()
    {
    }

    public static void Main(string[] args)
    {
        using (PDDocument document = Loader.LoadPDF(CreateSimpleForm.DefaultFilename))
        {
            PDAcroForm acroForm = document.GetDocumentCatalog().GetAcroForm()!;

            // Get the field and the widget associated to it.
            // Note: there might be multiple widgets
            PDField field = acroForm.GetFieldTree().First(f => f.GetPartialName() == "SampleField");
            PDAnnotationWidget widget = field.GetWidgets()[0];

            // Get the width of the fields box
            float widthOfField = widget.GetRectangle()!.GetWidth();

            // Get the font and the font size setting from the default appearance string
            // e.g. "/Helv 12 Tf 0 g"
            string defaultAppearance = ((PDTextField)field).GetDefaultAppearance()!;
            string[] parts = defaultAppearance.Split(' ');

            // Get the font name
            COSName fontName = COSName.GetPDFName(parts[0].Substring(1));
            float fontSize = float.Parse(parts[1], System.Globalization.CultureInfo.InvariantCulture);

            // Get the font resource.
            // First look up the font from the widget's appearance stream (if a value has been set).
            // If not present yet, look in the AcroForm default resources.
            PDFont? font = null;
            PDResources? resources = widget.GetNormalAppearanceStream()?.GetResources();
            if (resources != null)
            {
                font = resources.GetFont(fontName);
            }
            if (font == null)
            {
                font = acroForm.GetDefaultResources()?.GetFont(fontName);
            }

            string willFit = "short string";
            string willNotFit = "this is a very long string which will not fit the width of the widget";

            // calculate the string width at a certain font size
            float willFitWidth = font!.GetStringWidth(willFit) * fontSize / 1000;
            float willNotFitWidth = font.GetStringWidth(willNotFit) * fontSize / 1000;

            Console.WriteLine($"'{willFit}' fits: {willFitWidth < widthOfField}");
            Console.WriteLine($"'{willNotFit.Substring(0, 20)}...' fits: {willNotFitWidth < widthOfField}");
        }
    }
}
