/*
 * Copyright (c) 2026 Erik A. Brandstadmoen (C# port modifications/adaptations).
 * Mechanically converted from Apache PDFBox Java source with AI assistance.
 *
 * PDFBOX_SOURCE_PATH: pdfbox/src/main/java/org/apache/pdfbox/pdfwriter/COSWriterXRefEntry.java
 * PDFBOX_SOURCE_COMMIT: 2.0 branch (class removed from trunk during 3.x refactor)
 * PORT_MODE: mechanical
 * PORT_LAST_SYNC_COMMIT: 2.0 branch
 */

/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using PdfBox.Net.COS;

namespace PdfBox.Net.PdfWriter;

/// <summary>
/// An entry in the xref section of the physical PDF document generated by the <see cref="COSWriter"/>.
/// </summary>
/// <remarks>Author: Michael Traut</remarks>
public class COSWriterXRefEntry : IComparable<COSWriterXRefEntry>
{
    private static readonly COSWriterXRefEntry NullEntry;

    static COSWriterXRefEntry()
    {
        NullEntry = new COSWriterXRefEntry(0, null, new COSObjectKey(0, 65535));
        NullEntry.IsFree = true;
    }

    /// <summary>
    /// Constructs a new xref entry.
    /// </summary>
    /// <param name="start">The byte offset of the object in the PDF file.</param>
    /// <param name="obj">The COS object that this entry represents.</param>
    /// <param name="key">The object key.</param>
    public COSWriterXRefEntry(long start, COSBase? obj, COSObjectKey key)
    {
        Offset = start;
        Object = obj;
        Key = key;
    }

    /// <summary>Returns the null xref entry: <c>0000000000 65535 f</c>.</summary>
    public static COSWriterXRefEntry GetNullEntry() => NullEntry;

    /// <summary>Gets the object key.</summary>
    public COSObjectKey Key { get; private set; }

    /// <summary>Gets or sets the byte offset of the object within the PDF file.</summary>
    public long Offset { get; set; }

    /// <summary>Gets or sets whether this entry is a free (deleted) object.</summary>
    public bool IsFree { get; set; }

    /// <summary>Gets the COS object represented by this entry.</summary>
    public COSBase? Object { get; private set; }

    /// <inheritdoc/>
    public int CompareTo(COSWriterXRefEntry? other)
    {
        if (other == null)
        {
            return -1;
        }
        long thisNum = Key.GetNumber();
        long otherNum = other.Key.GetNumber();
        return thisNum < otherNum ? -1 : thisNum > otherNum ? 1 : 0;
    }
}
