// Operator processors have been moved to their canonical per-class files:
//
//   ContentStream/Operator/OperatorProcessor.cs
//   ContentStream/Operator/DrawObject.cs
//   ContentStream/Operator/State/Concatenate.cs
//   ContentStream/Operator/State/Restore.cs
//   ContentStream/Operator/State/Save.cs
//   ContentStream/Operator/State/SetGraphicsStateParameters.cs
//   ContentStream/Operator/State/SetMatrix.cs
//   ContentStream/Operator/Text/BeginText.cs
//   ContentStream/Operator/Text/EndText.cs
//   ContentStream/Operator/Text/MoveText.cs
//   ContentStream/Operator/Text/MoveTextSetLeading.cs
//   ContentStream/Operator/Text/NextLine.cs
//   ContentStream/Operator/Text/SetCharSpacing.cs
//   ContentStream/Operator/Text/SetFontAndSize.cs
//   ContentStream/Operator/Text/SetTextHorizontalScaling.cs
//   ContentStream/Operator/Text/SetTextLeading.cs
//   ContentStream/Operator/Text/SetTextRenderingMode.cs
//   ContentStream/Operator/Text/SetTextRise.cs
//   ContentStream/Operator/Text/SetWordSpacing.cs
//   ContentStream/Operator/Text/ShowText.cs
//   ContentStream/Operator/Text/ShowTextAdjusted.cs
//   ContentStream/Operator/Text/ShowTextLine.cs
//   ContentStream/Operator/Text/ShowTextLineAndSpace.cs
//   ContentStream/Operator/MarkedContent/BeginMarkedContentSequence.cs
//   ContentStream/Operator/MarkedContent/BeginMarkedContentSequenceWithProperties.cs
//   ContentStream/Operator/MarkedContent/EndMarkedContentSequence.cs
//   ContentStream/Operator/MarkedContent/MarkedContentPoint.cs
//   ContentStream/Operator/MarkedContent/MarkedContentPointWithProperties.cs
